name: 🚀 Release
on:
  push:
    branches:
      - main

jobs:
  # init-cache:
  #     name: 📦 Cache Yarn Packages
  #     runs-on: ubuntu-latest

  #     steps:
  #       - name: 🚚 Checkout
  #         uses: actions/checkout@v3

  #       - name: 🔧 Setup Node
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: "16"
  #           cache: "yarn"

  #       - name: 💾 Installing packages
  #         run: yarn install

  release:
    name: 🚀 Release @atws packages
    runs-on: ubuntu-latest
    # needs: [init-cache]

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3

      - name: 🔧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: 💾 Installing packages
        run: yarn install

      - name: 📦 Build packages
        run: yarn run build

      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run release
